global:
  imageRegistry: "sujeet9242026acr.azurecr.io"
  imagePullPolicy: IfNotPresent
imagePullSecrets: []
imageTag: latest
services:
  orderApi:
    image: order-api
    port: 3000
    replicas: 2
  orderProcessor:
    image: order-processor
    replicas: 1
  notificationService:
    image: notification-service
    replicas: 1
storageConnectionString: ""
